### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ShadowZPT** [kaaaxcreators/omegleip#2]
An error occured. (HTTP Statuscode: 403)
External Information about 128.201.219.45

![image](https://user-images.githubusercontent.com/26262540/102232196-b8dfb180-3ee6-11eb-8ced-619eae7fca6b.png)

**Comment by kaaax0815** [comment]
Do you have the newest Version of Omegle IP? (0.9)
Did you provide your own api key?

**Comment by kaaax0815** [comment]
Closed, because of inactivity.
