### ISSUE TITLE
HTTP Error 403

### ISSUE THREAD

**Issue by hugocar2005** [kaaaxcreators/omegleip#4]
It worked fine the first ~10 times, but now it says this: "An error occured, when before you exceeded your daily quata. (HTTP Statuscode: 403) External Information about * ip *"

**Comment by kaaax0815** [comment]
I'll look into that.

**Comment by kaaax0815** [comment]
@hugocar2005 I updated it everywhere. Update to Version `1.3`.

**Comment by hugocar2005** [comment]
not it just spams something and ends up like this: 
![image](https://user-images.githubusercontent.com/81335345/112550700-aadbdf80-8db7-11eb-8a3c-72c3e88c7411.png)

(im using "OmegleIP - API - Tracker - NoConsole.js" btw)

**Comment by kaaax0815** [comment]
The Scripts are Discontinued, because the Extension and Userscript are more used. But because of the new api, I'll update them

**Comment by kaaax0815** [comment]
@hugocar2005 Updated the Script to `v1.3` should now work!

**Comment by hugocar2005** [comment]
Yeah it's working now, thanks.
