### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Mineplayerminer** [kaaaxcreators/omegleip#6]
Im getting this error whenever I send any of those Java scripts:

ƒ (...args) {
	const pc = new window.oRTCPeerConnection(...args)
	pc.oaddIceCandidate = pc.addIceCandidate
	pc.addIceCandidate = function(iceCandidate, ...rest) {
		const fields = iceCandidate.candidat…

**Comment by kaaax0815** [comment]
Please specify which version you are using
This is just the response from the function which is totally fine.

**Comment by kaaax0815** [comment]
@Mineplayerminer could you provide more information?

**Comment by Mineplayerminer** [comment]
I fixed it. The Java was out of date.

**Comment by kaaax0815** [comment]
Thats great, but java has nothing do to with the script. javascript is complete seperate from java from oracle

**Comment by b-7307** [comment]
Shows the IP and Geolocation of the stranger. Written in Javascript as a Extension
Is.
Is this also possible with a script for the site markplaats.nl? 
Already thanks

**Comment by b-7307** [comment]
Alright, thank you for your quick reply!
Greetz
