### ISSUE TITLE
Error 429 even after new api

### ISSUE THREAD

**Issue by Minty64** [kaaaxcreators/omegleip#7]
Hello Dev, i tried using your extension on opera but it does not work showing error 429, I added my new API and still not working. 
![image](https://user-images.githubusercontent.com/57541059/125069160-023a5d00-e0d4-11eb-8118-4b7937e35cc0.png)
![image](https://user-images.githubusercontent.com/57541059/125069382-4c234300-e0d4-11eb-98ad-c839b5feb796.png)

**Comment by kaaax0815** [comment]
Please tell which version of the Extension you are using. As you are using Opera I would say you are using the Extension from Opera Add-ons. Is that correct?

**Comment by Minty64** [comment]
yes, I am using 1.3

**Comment by kaaax0815** [comment]
Did you check your API Usage on [Big Data Cloud](https://www.bigdatacloud.com/customer/account)?

**Comment by Minty64** [comment]
Just checked 0

**Comment by kaaax0815** [comment]
Ill check into that asap

**Comment by kaaax0815** [comment]
Fixed the Issue publishing it ASAP

**Comment by kaaax0815** [comment]
Uploaded the Extension to Opera Addons. Should now be available. Update and check if the issue persists
